# 多数据源数据库配置 @EnableJpaRepositories注解只需要在配置类中使用，不能在启动类中使用
demo:
  datasource:
    mysql:
      url: jdbc:mysql://127.0.0.1:3306/test?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        database: mysql
        show-sql: true
        properties:
          dialect: org.hibernate.dialect.MySQL5Dialect
          hbm2ddl.auto: update

    postgre:
      url: jdbc:postgresql://127.0.0.1:5432/panda_main?tcpKeepAlive=true&autoReconnect=true&PGTZ=8
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
      jpa:
        database: postgresql
        show-sql: true
        properties:
          hbm2ddl.auto: update
          dialect: org.hibernate.dialect.PostgreSQLDialect
          temp:
            use_jdbc_metadata_defaults: false
          hibernate.physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
          hibernate.implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy