#####
# config_document:
  # https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
#####

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: demo
  redis:
    host: 127.0.0.1
    port: 6379
# java -jar xxx.jar --spring.profiles.active={profile} 切换不同的环境配置
  profiles:
    active: dev
    include: prop-test,data-plural #,data

# 项目启动时可以通过命令行参数改变端口的值
# java -jar xxx.jar --server.port=8081
server:
  port: 6324
  servlet:
    context-path: /demo

### logging
# logging.config=
logging:
  file: application.log
  path: /tmp/${spring.application.name}
  level:
    com.example.demo: debug
  # 不配置好像也能生效
  config: classpath:logback-spring.xml